export c_woff2 from './Calibre-Regular.woff2';
export c_woff from './Calibre-Regular.woff';
export c_ttf from './Calibre-Regular.ttf';
export s_woff2 from './SuezOne-Regular.woff2';
export s_woff from './SuezOne-Regular.woff';
export s_ttf from './SuezOne-Regular.ttf';
export i_woff2 from './Inconsolata-Regular.woff2';
export i_woff from './Inconsolata-Regular.woff';
export i_ttf from './Inconsolata-Regular.ttf';